name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - 'main'
      - 'chore-ci'

jobs:
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
      - name: Test
        run: ./scripts/audit.sh
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: @angular/dev-infra/actions/setup-node@v4
        with:
          node-version: 18.18.2
      - run: npm install -g @angular/cli
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: ng lint app
  deploy-pr-preview:
    name: deploy preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: @angular/dev-infra/actions/setup-node@v4
        with:
          node-version: 18.18.2
      - run: npm install -g @angular/cli
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        run: yarn build-prod
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          alias: ec-decoupled-frontend${{ github.event.number }}
          publish-dir: 'dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  deploy-branch-preview:
    name: deploy branch
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: @angular/dev-infra/actions/setup-node@v4
        with:
          node-version: 18.18.2
      - run: npm install -g @angular/cli
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Package application
        run: yarn build-prod
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          alias: ${{ github.ref_name }}
          publish-dir: 'dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
